spcl/dace-vscode

src/daceInterface.ts
src/extension.ts
src/transformation/transformation.ts
src/transformation/transformationsProvider.ts

Fixes for transformation interface

---

CHANGELOG.md
backend/run_dace.py
media/sdfv_base_layout.html
package.json
src/daceInterface.ts
src/extension.ts
src/sdfg_viewer.ts

- Moves the interface to DaCe in to the plugin and out of DaCe itself
- Provide API calls to facilitate the functionality for the webclient's new FLOPS overlay

Provide DaCe interface for the new FLOPS overlay

---

backend/run_dace.py
media/components/outline/outline.css
media/outline_base_layout.html
media/sdfv_base_layout.html
media/sdfv_embedded_overrides.js
package-lock.json
package.json
src/daceInterface.ts
src/extension.ts
src/sdfg_viewer.ts
src/viewer/outlineProvider.ts

- Use a separate webview view panel to display SDFG outlines
- Outline automatically shows when an SDFG is displayed
- Provides a refresh button to refresh the outline if the SDFG has changed
- Automatically clear and refresh the outline when the shown SDFG is switched

Provide a separate view panel for SDFG outlines

---

media/components/outline/index.html
media/components/sdfv/index.html
media/components/sdfv/sdfv_overrides.js
media/components/symbol_resolution/index.html
media/components/symbol_resolution/symbol_resolution.css
media/components/symbol_resolution/symbol_resolution.js
package.json
src/components/baseComponent.ts
src/components/messaging/componentMessageHandler.ts
src/components/messaging/messageReceiverInterface.ts
src/components/outline.ts
src/components/sdfgViewer.ts
src/components/symbolResolution.ts
src/daceInterface.ts
src/extension.ts

- Provide an additonal WebviewView panel to indicate and change current symbol definitions
- Allows for changing the settings of how the analysis overlays highlight the graph

Provide a separate panel with symbol definitions and settings for analysis overlays

---

CHANGELOG.md
backend/run_dace.py
media/components/sdfv/messaging/message_handler.js
media/components/sdfv/transformation/transformation.js
media/components/transformation_list/index.html
media/components/transformation_list/transformation_list.js
package-lock.json
package.json
src/daceInterface.ts
src/debugger/sdfgPythonRuntime.ts

Smaller bugfixes for transformation lists and message passing

---

AUTHORS
CHANGELOG.md
CODE_OF_CONDUCT.md
media/components/sdfv/index.html
package.json
src/components/OptimizationPanel.ts
src/components/outline.ts
src/components/transformationHistory.ts
src/components/transformationList.ts
src/daceInterface.ts

This closes #12.
Additionally adds a code of conduct and authors list file.

Remove the 'DaCe Daemon not running' notification when not optimizing

---

backend/run_dace.py
package.json

Fixes a new bug introduced in #43

Remove wrongful static method check

---

media/components/sdfv/transformation/transformation.js
media/components/sdfv/vscode_sdfv.js

Closes #23
Depends on https://github.com/spcl/dace-webclient/pull/38

Improve subgraph transformation loading/unloading

---

backend/run_dace.py
media/components/sdfv/sdfv_overrides.css
media/components/sdfv/vscode_sdfv.js
src/daceInterface.ts

This closes #48.
Note: Expansions don't appear in an SDFG's transformation history without https://github.com/spcl/dace/pull/750

Add a button to library nodes to expand them

---

CHANGELOG.md
backend/run_dace.py
media/components/sdfv/properties/properties.js
media/components/sdfv/sdfv_overrides.css
media/components/sdfv/sdfv_overrides.js
media/components/sdfv/transformation/transformation.js
media/components/sdfv/vscode_sdfv.js
package.json

- Add delete buttons to list, dictionary, and range inputs in property editing
- Allow property editing for transformations before applying

Provide editable transformation properties and delete buttons for list/dict/range properties

---

media/components/sdfv/index.html
media/components/sdfv/properties/properties.js
media/components/sdfv/sdfv_overrides.css
media/components/sdfv/vscode_sdfv.js
package-lock.json

Transition to Monaco-Editor for Code properties

---

media/components/transformation_history/transformation_history.css
media/components/transformation_list/transformation_list.css
media/components/transformation_list/transformation_list.js

Allow Quick-Applying of transformations with default parameters

---

media/components/analysis/index.html
media/components/sdfv/analysis/analysis.js
media/components/sdfv/breakpoints/breakpoints.js
media/components/sdfv/index.html
media/components/sdfv/messaging/message_handler.js
package-lock.json

Update SDFV to remove booleans from the overlay manager

---

CHANGELOG.md
backend/dace_vscode/transformations.py
media/components/sdfv/messaging/message_handler.js
media/components/sdfv/transformation/transformation.js
media/components/sdfv/util/vscode_renderer.js
media/components/sdfv/vscode_sdfv.js
media/components/transformation_list/transformation_list.js
package-lock.json
package.json

Depends on https://github.com/spcl/dace-webclient/pull/45.

Fixes transformation list refresh when viewport moves with multi select

---

CHANGELOG.md
package.json
src/webclients/components/sdfv/transformation/transformation.ts
src/webclients/components/transformations/transformations.ts

Properly sort transformations

---

package-lock.json
package.json

Everything works as intended with cutouts. Of course, some adaptations will need to be made to make full use of the feature down the road:
- Update transformations to apply only to cutout region (if sensible)
- Save-/Edit-Action upon cutout

Update the webclient

---

backend/run_dace.py
media/components/analysis/index.html
package-lock.json
src/webclients/components/analysis/analysis.css
src/webclients/components/analysis/analysis.ts
src/webclients/components/sdfv/analysis/analysis.ts
src/webclients/components/sdfv/messaging/message_handler.ts
src/webclients/components/sdfv/vscode_sdfv.css
src/webclients/components/sdfv/vscode_sdfv.ts

- Fixes bug with invalid loading of pythonpath from .env files in the backend
- Implements new overlays from the webclient
- Add interpolation scaling
- Switches the UI for changing scaling methods

Add linear and exponential interpolation to overlay scaling methods, updates SDFV

---

package.json

Meant to be part of the June fixes.

Add compressed extensions to SDFG

---

CHANGELOG.md
backend/dace_vscode/transformations.py
backend/run_dace.py
media/components/sdfv/index.html
package-lock.json
package.json
src/components/sdfg_viewer.ts
src/dace_interface.ts
src/extension.ts
src/utils/sdfg_meta_dict.json
src/utils/utils.ts
src/webclients/components/sdfv/messaging/message_handler.ts
src/webclients/components/sdfv/properties/properties.ts
src/webclients/components/sdfv/renderer/vscode_renderer.ts
src/webclients/components/sdfv/transformation/transformation.ts
src/webclients/components/sdfv/utils/attributes_table.ts
src/webclients/components/sdfv/utils/helpers.ts
src/webclients/components/sdfv/vscode_sdfv.css
src/webclients/components/sdfv/vscode_sdfv.ts
src/webclients/components/transformations/transformations.css
src/webclients/components/transformations/transformations.ts
src/webclients/elements/treeview/treeview.ts

Companion PR https://github.com/spcl/dace-webclient/pull/89 closes #187.
NOTE: Only one improvements patch is planned for the month of August. This is an exception.

August Improvements

---

media/components/sdfv/index.html
src/components/sdfg_editor/common.ts
src/webclients/components/sdfv/utils/attributes_table.ts
src/webclients/components/sdfv/vscode_sdfv.css
src/webclients/components/sdfv/vscode_sdfv.ts

Minimap and info tray improvements

---

src/components/dace_interface.ts
src/webclients/components/sdfv/properties/properties.ts
src/webclients/components/sdfv/utils/attributes_table.ts
src/webclients/components/sdfv/vscode_sdfv.ts

June Fixes

---

media/components/analysis/index.html
src/components/analysis.ts
src/webclients/components/analysis/analysis.ts

Allow loading runtime reports through VSCode's File API

---

backend/dace_vscode/work_depth.py
package-lock.json
package.json
src/webclients/components/dace/dace_panel.ts

Fix work depth analysis dependency

---

package-lock.json
package.json
src/utils/sdfg_meta_dict.json
src/webclients/components/sdfv/breakpoints/breakpoints.ts
src/webclients/components/sdfv/utils/attributes_table.ts

Depends on: https://github.com/spcl/dace-webclient/pull/160

Various Bugfixes
